### ISSUE TITLE
feedback from projects site

### ISSUE THREAD

**Issue by martinohanlon** [raspberrypilearning/getting-started-with-picamera#10]
URL: /en/projects/getting-started-with-picamera/4

This page, https://projects.raspberrypi.org/en/projects/getting-started-with-picamera/4, does not explain that the camera port has a plastic part that needs to be lifted up in order to get the cable inserted. I almost broke my cable trying to force it in. The instruction "Locate the camera port and connect the camera" needs to be expanded to explain how to open the port.

**Comment by lawsie** [comment]
PR to fix this in progress. #11
