### ISSUE TITLE
Needed sudo

### ISSUE THREAD

**Issue by mattiasw2** [raspberrypilearning/getting-started-with-picamera#4]
In order to get this to work in PI3 with PiNoir camera v2 using Ubuntu Mate, I had to do sudo, for example starting idle3 using 'sudo idle3'

Otherwise I get errors like "* failed to open vchiq instance"

**Comment by bennuttall** [comment]
This is an issue with Ubuntu MATE, not an issue with this resource. You shouldn't need sudo to use the camera. We only support Raspbian in our materials.
