### ISSUE TITLE
Misspelling of video.h264 as vide.h264

### ISSUE THREAD

**Issue by JamesH65** [raspberrypilearning/getting-started-with-picamera#6]
In the image on this page https://github.com/raspberrypilearning/getting-started-with-picamera/blob/master/en/step_7.md video.h264 is mispelt as vide.h264

**Comment by martinohanlon** [comment]
@JamesH65 - can you point me in the right direction here?  I cant find the misspelling? Am I looking in the right place?

**Comment by martinohanlon** [comment]
Closing. I cant find an instance of vide.h264 in either draft or branch in any step.

**Comment by JamesH65** [comment]
In this image https://github.com/raspberrypilearning/getting-started-with-picamera/blob/master/en/images/omxplayer.png

**Comment by martinohanlon** [comment]
thank you

**Comment by martinohanlon** [comment]
fixed in [commit](https://github.com/raspberrypilearning/getting-started-with-picamera/commit/a9c9de1da9a8815ed205bf06310ed10dec19cc6c)
